use syncdb;

ALTER TABLE Files
  ADD COLUMN Version INT NOT NULL DEFAULT 1;

ALTER TABLE Folders
  ADD COLUMN Version INT NOT NULL DEFAULT 1;

CREATE TABLE IF NOT EXISTS Changes (
  Seq BIGINT AUTO_INCREMENT PRIMARY KEY,
  EntityType ENUM('FILE','FOLDER') NOT NULL,
  EntityId INT NOT NULL,
  ChangeType ENUM('CREATE','UPDATE','DELETE','RENAME','MOVE') NOT NULL,
  Version INT NOT NULL,
  FileHash VARCHAR(64) NULL,
  Size BIGINT NULL,
  FolderId INT NULL,
  FileName VARCHAR(255) NULL,
  UserId INT NULL,
  At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_changes_seq ON Changes(Seq);